import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TypingProvider } from "@/context/typing-context";
import { ThemeProvider } from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TypePulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ThemeProvider>
          <TypingProvider>{children}</TypingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
